AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro

  ImageId:
    Type: String

  KeyName:
    Type: String

  SubnetId:
    Type: String

  SecurityGroupId:
    Type: String

Resources:
  NetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref SubnetId
      GroupSet:
        - !Ref SecurityGroupId

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - DeviceIndex: 0
          NetworkInterfaceId: !Ref NetworkInterface
      Tags:
        - Key: Name
          Value: PrivateServer
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        amazon-linux-extras install nginx1.12 -y
        service nginx start
        echo "<div><h1>PRIVATE-SERVER</h1></div>" >> /usr/share/nginx/html/index.html
        echo "<div><h1>DEV-OPS 2023</h1></div>" >> /usr/share/nginx/html/index.html

Outputs:
  InstanceId:
    Value: !Ref EC2Instance

  PrivateIP:
    Value: !GetAtt EC2Instance.PrivateIp